name: Test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  test:
    name: Rspec Test Action
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 3.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2
      env:
        ImageOS: ubuntu-latest
    - name: Bundle
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
      env:
        ImageOS: ubuntu-latest
    - name: Run Rspec
      run: bin/rspec
